### ISSUE TITLE
Test 시 spring이 .env.local을 인식하지 못하는 문제

### ISSUE THREAD

**Issue by haxr369** [spring-templates/spring-concurrency-jpa#10]
**Describe the bug**
#7 [커밋](https://github.com/spring-templates/spring-concurrency-jpa/pull/7/commits/095713f378bdf9a09f3b36b529a6460674333215)에서 test 시 spring이 .env.local 파일의 값을 읽지 못하는 문제가 발생

**To Reproduce**

1. `SpringConcurrencyApplication`으로 DB 테이블 생성
1. Go to 'OrderRepositoryTest'
2. Click on 'Order_Create_AND_SELECT_Test'

**Expected behavior**

```
Caused by: java.net.UnknownHostException: ${MYSQL_SERVER}: nodename nor servname provided, or not known
```

**Screenshots**

**Additional context**

.env.local이 어느 profile에서 spring에 적용되는건지 잘 모르겠습니다.

**Comment by ooMia** [comment]
## 해결책

1. `.env.local`에서 MYSQL_SERVER의 값을 dev로 설정

또는

2. `.env.local`에서 MYSQL_SERVER의 값을 localhost로 설정
    - `docker-compose.yaml` 파일 수정: 각 서비스에서 다음 절을 모두 삭제
    
        ```yaml
            networks:
              - private-subnet
        ```

## 설명

아마도 `.env.local`에서 MYSQL_SERVER의 값을 localhost로 했으리라 생각합니다.

이 경우 오류의 원인은 `docker-compose.yaml`의 private-network 때문입니다.

app 자체가 private-network에서 동작할 것으로 정의된 상태이기 때문에 localhost를 사용하면 standalone db를 사용하지 못하는 상태입니다.

따라서, network 설정을 바꿔주면 정상적으로 동작합니다.


### 추가 설명

`.env.local` 파일은 프로젝트의 전역 변수를 관할합니다.
이는 Profile에 관계없이 적용됩니다.

`.env.local` 파일의 환경 변수는
`docker-compose.yaml` 파일을 통해 애플리케이션에 전달됩니다.

애플리케이션으로 전달된 환경변수를
`application.yml`이 활용하여 설정을 진행합니다.

**Comment by ooMia** [comment]
다수의 기기를 마음대로 사용할 수 없는 환경에서는, 각 기기에서 다수의 서비스가 동시에 동작하는 상황이 발생하고, 이 때 네트워크를 분리해두면 운영 환경을 관리할 때 용이하다고 생각합니다.

따라서, `.env.local`에서 MYSQL_SERVER 값을 `dev`로 사용하는 것을 권장합니다.

**Comment by ooMia** [comment]
테스트 환경에서만 동작하지 않는다면
`@SpringBootTest` 어노테이션을 설정했는지 확인하고,

추가로 `.env.local`에 대한 값은 프로필과 관계없이 적용되는 값으로 설정해두었습니다.
`application.yml` 파일을 확인하세요

```yml
#
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
#

# this is a global configuration file
# no options are overridden here

# Core configuration
spring.application.name: spring-web-jpa-concurrency
spring.profiles.active: default, dev, init-sql

# Database configuration
spring.datasource:
  url: jdbc:mysql://${MYSQL_SERVER}:3306/${MYSQL_DATABASE}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
```
